repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: '79fc0d8d67e291b445a60a4a31a6ccabb5049e48'  # Use the sha / tag you want to point at
    hooks:
      - id: yapf