version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python -m pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            python -m pytest --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build:
    jobs:
      - build